name: CI

on: [push]

env:
  NODE_ENV: test
  DATABASE_URL: postgresql://postgres:postgres@localhost/myapp_test?schema=ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.13.2
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: ESLint
        run: yarn lint

      - name: Check TypeScript
        run: yarn typecheck

      # Build app
      - name: Build App
        run: yarn build

      # Save build for other jobs
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: the-build
          if-no-files-found: error
          path: build
          retention-days: 1
